### ISSUE TITLE
Benchmark or Test Suite to evaluate FAME

### ISSUE THREAD

**Issue by bhyunki** [FabricAttachedMemory/Emulation#28]
Is there any Benchmark or test suite through which we can evaluate FAME in terms of performance, latency and throughput? 
And which module in this emulation are implementing Gen-Z memory controller?

Thanks in advance for your time and response.

**Comment by coloroco** [comment]
FAME was never intended to be a performant environment.  It is a sufficiently accurate emulation of "configured" virtual hardware so that software development could occur.  Said software then runs directly on The Machine without modification, and The Machine is where we did benchmarking.

That being said, performance will depend primarily on the total memory of your VM host.   QEMU uses memory mapping to manage the backing file.   Linux will page memory in and out as necessary when it runs out of available memory.   The FAME environment could have a maxium working size of the backing file plus the "Virtual DRAM" of all running nodes.  If you have at least twice that much real DRAM installed in your VM host, eventually of the the nodes "VDRAM" and FAM will be in real memory.  That would be the most accurate representation of real hardware, but it's not really to draw any correlation from that.

As for the memory controller (aka "media controller" in The Machine parlance) there is no emulation of that hardware in FAME.  In fact it is "assumed out of existence" as properly configured hardware looks invisible to load-store activity.   [Refer to the following wiki page](https://github.com/FabricAttachedMemory/Emulation/wiki/Emulation-and-Simulation).

**Comment by coloroco** [comment]
Closing due to lack of further discussion.
